DjangoLevelFour/DjangoLevelFour/urls.py
"""
Definition of urls for DjangoLevelFour.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    #url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^',include('LearningTemplates.urls')),
     url(r'^US/',include('LearningUsers.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]

DjangoLevelFour/LearningTemplates/urls.py
"""
Definition of urls for DjangoLevelFour.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

from LearningTemplates import views
import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
# admin.autodiscover()

# template tagging app_name variable
app_name = 'LearningTemplates'


urlpatterns = [
    # Examples:
    #url(r'^$', app.views.home, name='home'),

    url(r'^$', views.index, name='index'),
    url(r'^other/$', views.other, name='other'),
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^',include('LearningUsers.urls')),

    ]

DjangoLevelFour/LearningUsers/urls.py
"""
Definition of urls for DjangoLevelFour.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

from LearningUsers import views
import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
# admin.autodiscover()

# template tagging app_name variable
app_name = 'LearningUsers'


urlpatterns = [
    # Examples:
    #url(r'^$', app.views.home, name='home'),

    url(r'^Registration/', views.Register, name='Register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    

    ]

DjangoLevelFour/LearningTemplates/models.py
from django.db import models

# Create your models here.

DjangoLevelFour/LearningUsers/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfoClass(models.Model):
    #to add more attributes
    user=models.OneToOneField(User)

    #additional classes
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username


# Create your models here.

DjangoLevelFour/app/models.py
"""
Definition of models.
"""

from django.db import models

# Create your models here.

DjangoLevelFour/LearningUsers/forms.py
from django import forms
from django.contrib.auth.models import User
from LearningUsers.models import UserProfileInfoClass

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoClassForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfoClass
        fields=('portfolio_site','profile_pic')

DjangoLevelFour/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

DjangoLevelFour/LearningTemplates/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    #create a context dictionary
    context_dict ={'text':'Hello world','number':100}
    return render(request,'index.html',context=context_dict)

def other(request):
    return render(request,'other.html')

def relative(request):
    return render(request,'relative_url_templates.html')

DjangoLevelFour/LearningUsers/views.py
from django.shortcuts import render
from LearningUsers.forms import UserForm
from LearningUsers.forms import UserProfileInfoClassForm

from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from LearningTemplates.views import index


# Create your views here.
def  Register(request):
    #create a context dictionary
    #return render(request,'UserIndex.html')
    registered=False
    if request.method=='POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoClassForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save() #save the user to the DB
            user.set_password(user.password) # Hashing the password
            user.save() #save the changes to the users

            profile=profile_form.save(commit=False)#stop the saving on the db to avoid colllisions
            profile.user = user # set up the one to one relationship with the user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered=True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form=UserProfileInfoClassForm()

    return render(request,'Registration.html',
                  {'user_form':user_form,
                  'profile_form':profile_form,
                  'registered':registered                  
                  })


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('LearningTemplates:index'))


def  user_login(request):
    #create a context dictionary
    
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('LearningTemplates:index'))
            else:
                return HttpResponse("account not active")
        else:
            print("someone tried to log in and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request,'LogIn.html')

DjangoLevelFour/app/views.py
"""
Definition of views.
"""

from django.shortcuts import render
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime

def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/index.html',
        {
            'title':'Home Page',
            'year':datetime.now().year,
        }
    )

def contact(request):
    """Renders the contact page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/contact.html',
        {
            'title':'Contact',
            'message':'Your contact page.',
            'year':datetime.now().year,
        }
    )

def about(request):
    """Renders the about page."""
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'app/about.html',
        {
            'title':'About',
            'message':'Your application description page.',
            'year':datetime.now().year,
        }
    )

DjangoLevelFour/LearningTemplates/templates/base.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                
                <li><a class="navbar-brand" href="{% url 'LearningTemplates:index' %}">KALI</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'LearningTemplates:other' %}">Other</a></li>
                <li><a class="navbar-link" href="{% url 'LearningUsers:Register' %}">Register</a></li>
                
                {% if user.is_authenticated %}

                <li><a class="navbar-link" href="{% url 'LearningUsers:user_logout' %}">Logout</a></li>
                {% else %}
                 <li><a class="navbar-link" href="{% url 'LearningUsers:user_login' %}">Login</a></li>
                {% endif %}

            </ul>
        </div>

        

    </nav>

    <div class="container">
            
            {% block body_block %}
            <!--Anything outside of this will be inerhited-->
            {% endblock %}
        </div>

</body>
</html>

DjangoLevelFour/LearningTemplates/templates/index.html
<!DOCTYPE html>


{% extends "base.html" %}
    {% block body_block %}
        <h1> Welcome to hme page </h1>
        <!--<h2>This is is index.html showing</h2>-->
          {% if user.is_authenticated %}

                <h3>Welcome {{user.get_username }}</h3>
                {% else %}
                 <h3>Loggati sfigato</h3>
                {% endif %}

        <h1>{{text|upper}}</h1>
        <h1>{{number|add:"99"}}</h1>
        <h1>{{text|cut:"Hello"}}</h1>
    {% endblock%}

DjangoLevelFour/LearningTemplates/templates/other.html
<!DOCTYPE html>

{% extends "base.html" %}
    {% block body_block %}
    <h1> Welcome to others </h1>
    <h2>This is an example of template inheritance</h2>
    {% endblock%}

DjangoLevelFour/LearningTemplates/templates/relative_url_templates.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1> Welcome to relative url templates</h1>

    <a href="{% url 'LearningTemplates:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">The admin page</a>
    <a href="{% url 'LearningTemplates:index' %}">The index page</a>

</body>
</html>

DjangoLevelFour/LearningUsers/templates/LogIn.html
<!DOCTYPE html>


{% extends "base.html" %}
    {% block body_block %}
        
        <div class="jumbotron">
            <h1> Please log in</h1>
            <form action="{% url 'LearningUsers:user_login' %}" method="post">
                {%csrf_token%}
                <label for="username">Username:</label>
                <input type='text' name="username" placeholder="Enter username" />

                <label for="password">Password:</label>
                <input type='password' name="password"/>

                <input type='submit' value="Login"/>

            </form>
        </div>
        
    {% endblock%}

DjangoLevelFour/LearningUsers/templates/Registration.html
<!DOCTYPE html>


{% extends "base.html" %}
{% load staticfiles %}
    {% block body_block %}
        
        <div class="jumbotron">

            {% if registered %}
                <h1>Thank you for registering</h1>
            {% else %}
                <h1>Register here</h1>
                <h3>Fill out the form:</h3>
                
                <form  method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{user_form.as_p}}
                    {{profile_form.as_p}}
                    <input type="submit" name="" value="Register" />
                </form>
                
            {% endif %}

        </div>
        
    {% endblock%}

DjangoLevelFour/LearningUsers/templates/UserIndex.html
<!DOCTYPE html>


{% extends "base.html" %}
    {% block body_block %}
        <h1> Welcome to hme page </h1>
        <!--<h2>This is is index.html showing</h2>-->
        <h1>Siamo nella pagina di log in</h1>
    {% endblock%}

DjangoLevelFour/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

DjangoLevelFour/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

DjangoLevelFour/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Django</h1>
    <p class="lead">Django is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Django gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://www.djangobook.com/en/2.0/index.html">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>The Python Package Index is a repository of software for the Python programming language.</p>
        <p><a class="btn btn-default" href="https://pypi.org/">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Microsoft Azure</h2>
        <p>You can easily publish to Microsoft Azure using Visual Studio. Find out how you can host your application using a free trial today.</p>
        <p><a class="btn btn-default" href="http://azure.microsoft.com">Learn more &raquo;</a></p>
    </div>
</div>

{% endblock %}

DjangoLevelFour/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Application name</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - My Django Application</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

DjangoLevelFour/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

DjangoLevelFour/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}